=== glzr-io/zebar/resources/widget-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Zebar Widget Schema",
  "type": "object",
  "properties": {
    "htmlPath": {
      "type": "string"
    },
    "zOrder": {
      "type": "string",
      "enum": ["top_most", "normal", "bottom_most"]
    },
    "shownInTaskbar": {
      "type": "boolean"
    },
    "focused": {
      "type": "boolean"
    },
    "resizable": {
      "type": "boolean"
    },
    "transparent": {
      "type": "boolean"
    },
    "caching": {
      "type": "object",
      "properties": {
        "defaultDuration": {
          "type": "integer"
        },
        "rules": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "urlRegex": {
                "type": "string"
              },
              "duration": {
                "type": "integer"
              }
            }
          }
        }
      }
    },
    "privileges": {
      "type": "object",
      "properties": {
        "shellCommands": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "program": {
                "type": "string"
              },
              "argsRegex": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "presets": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "anchor": {
              "type": "string",
              "enum": [
                "top_left",
                "top_center",
                "top_right",
                "center_left",
                "center",
                "center_right",
                "bottom_left",
                "bottom_center",
                "bottom_right"
              ]
            },
            "offsetX": {
              "type": "string"
            },
            "offsetY": {
              "type": "string"
            },
            "width": {
              "type": "string"
            },
            "height": {
              "type": "string"
            },
            "monitorSelection": {
              "type": "object",
              "oneOf": [
                {
                  "properties": {
                    "type": {
                      "const": "all"
                    }
                  },
                  "required": ["type"],
                  "additionalProperties": false
                },
                {
                  "properties": {
                    "type": {
                      "const": "primary"
                    }
                  },
                  "required": ["type"],
                  "additionalProperties": false
                },
                {
                  "properties": {
                    "type": {
                      "const": "secondary"
                    }
                  },
                  "required": ["type"],
                  "additionalProperties": false
                },
                {
                  "properties": {
                    "type": {
                      "const": "index"
                    },
                    "match": {
                      "type": "integer",
                      "minimum": 0
                    }
                  },
                  "required": ["type", "match"],
                  "additionalProperties": false
                },
                {
                  "properties": {
                    "type": {
                      "const": "name"
                    },
                    "match": {
                      "type": "string"
                    }
                  },
                  "required": ["type", "match"],
                  "additionalProperties": false
                }
              ]
            },
            "dockToEdge": {
              "type": "object",
              "properties": {
                "enabled": {
                  "type": "boolean",
                  "default": false
                },
                "edge": {
                  "oneOf": [
                    {
                      "type": "string",
                      "enum": ["top", "right", "bottom", "left"]
                    },
                    {
                      "type": "null"
                    }
                  ],
                  "default": null
                },
                "windowMargin": {
                  "type": "string"
                }
              },
              "additionalProperties": false
            }
          },
          "required": [
            "name",
            "anchor",
            "offsetX",
            "offsetY",
            "width",
            "height",
            "monitorSelection"
          ]
        }
      ]
    }
  },
  "required": [
    "htmlPath",
    "zOrder",
    "shownInTaskbar",
    "focused",
    "resizable",
    "transparent",
    "presets"
  ]
}

=== glzr-io/zebar/examples/boilerplate-solid-ts/example.zebar.json
{
  "$schema": "https://github.com/glzr-io/zebar/raw/v2.7.0/resources/widget-schema.json",
  "htmlPath": "./dist/index.html",
  "zOrder": "normal",
  "shownInTaskbar": false,
  "focused": false,
  "resizable": false,
  "transparent": false,
  "privileges": {
    "shellCommands": [
      {
        "program": "echo",
        "argsRegex": ".*"
      },
      {
        "program": "chrome",
        "argsRegex": ".*"
      },
      {
        "program": "git",
        "argsRegex": ".*"
      },
      {
        "program": "cmd",
        "argsRegex": ".*"
      },
      {
        "program": "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe",
        "argsRegex": ".*"
      },
      {
        "program": "powershell",
        "argsRegex": ".*"
      },
      {
        "program": "powershellaa",
        "argsRegex": ".*"
      }
    ]
  },
  "presets": [
    {
      "name": "default",
      "anchor": "top_left",
      "offsetX": "0px",
      "offsetY": "0px",
      "width": "100%",
      "height": "40px",
      "monitorSelection": {
        "type": "all"
      },
      "dockToEdge": {
        "enabled": false,
        "edge": null,
        "windowMargin": "0px"
      }
    }
  ]
}
